apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitoring-svmon
spec:
  selector:
    matchLabels:
      app:  nginx-monitoring-sv
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
