apiVersion: v1
kind: Service
metadata:
  name: nginx-monitoring-sv
  labels:
    app: nginx-monitoring-sv
spec:
  type: NodePort
  selector:
    app: nginx-monitoring
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: web
    - name: metrics
      protocol: TCP
      port: 80
      targetPort: metrics
      
