 expose:
  type: ingress
  tls:
    enables: true
    secretName: harbor.34.77.123.99.nip.io
    notarySecretName: notary.34.77.123.99.nip.io
  ingress:
    hosts:
      core: harbor.34.77.123.99.nip.io
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-production"
notary:
  enabled: false