apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    key: app
spec:
  securityContext:
    runAsUser: 1001
  containers:
  - name: web
    image: ebabaev/web-app:new
    volumeMounts:
      - name: app
        mountPath: /app
    readinessProbe:
        httpGet:
          port: 8000
    livenessProbe:
        tcpSocket:
          port: 8000
  initContainers:
    - name: init-index-page
      image: busybox
      command:
        [
          "sh",
          "-c",
          "wget -O-  https://tinyurl.com/otus-k8s-intro | sh",
        ]
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}